#ifndef INVENTIX_LEXER_H
#define INVENTIX_LEXER_H

typedef enum {
    TOKEN_EOF,
    TOKEN_IDENTIFIER,
    TOKEN_STRING,
    TOKEN_INT_LITERAL,
    TOKEN_FLOAT_LITERAL,
    
    // Keywords
    TOKEN_KW_TABLE,
    TOKEN_KW_BANAO,
    TOKEN_KW_INSERT,
    TOKEN_KW_KARO,
    TOKEN_KW_SELECT,
    TOKEN_KW_JAHAN,
    TOKEN_KW_RAKHO,
    TOKEN_KW_DHUNDO,
    TOKEN_KW_NIKALO,
    TOKEN_KW_FROM,
    TOKEN_KW_VALUES,
    TOKEN_KW_INT,
    TOKEN_KW_FLOAT,
    TOKEN_KW_STRING_TYPE,
    TOKEN_KW_TEXT_TYPE,
    TOKEN_KW_BOOL_TYPE,
    TOKEN_KW_AUTO, // For Auto Increment
    TOKEN_KW_PRIMARY,
    TOKEN_KW_KEY,
    TOKEN_KW_GIRAO, // DROP
    TOKEN_KW_MANGWAO, // GET (NoSQL)
    TOKEN_KW_HATAO,   // DELETE (NoSQL)
    TOKEN_KW_CHECKPOINT, // Manual Snapshot
    TOKEN_KW_UPDATE,   // UPDATE
    TOKEN_KW_SET,      // SET

    TOKEN_KW_INDEX, // INDEX
    TOKEN_KW_ON,    // ON

    // Auth & System
    TOKEN_KW_CREATE,  // CREATE
    TOKEN_KW_USER,    // USER
    TOKEN_KW_PASSWORD, // PASSWORD
    TOKEN_KW_DATABASE, // DATABASE
    TOKEN_KW_show,     // SHOW
    TOKEN_KW_TABLES,   // TABLES
    TOKEN_KW_USE,      // USE

    // Logical & Grouping (Step 10)
    TOKEN_KW_AND,      // AUR
    TOKEN_KW_OR,       // YA
    TOKEN_KW_GROUP,    // SAMOOH
    TOKEN_KW_BY,       // DWARA
    TOKEN_KW_COUNT,    // GINO
    TOKEN_KW_SUM,      // JODO
    TOKEN_KW_AVG,      // AUSAAT
    TOKEN_KW_MIN,      // SABSE_CHOTA
    TOKEN_KW_MAX,      // SABSE_BADA

    // Transaction Keywords
    TOKEN_KW_BEGIN,    // BEGIN / SHURU
    TOKEN_KW_COMMIT,   // COMMIT / PUKKA
    TOKEN_KW_ROLLBACK, // ROLLBACK / WAPAS
    TOKEN_KW_SAVEPOINT,// SAVEPOINT
    TOKEN_KW_RELEASE,  // RELEASE
    TOKEN_KW_TRANSACTION, // TRANSACTION
    TOKEN_KW_START,    // START
    TOKEN_KW_TO,       // TO (for ROLLBACK TO)
    TOKEN_KW_INTO,     // INTO (for INSERT INTO)
    TOKEN_KW_ISOLATION, // ISOLATION
    TOKEN_KW_LEVEL,    // LEVEL
    TOKEN_KW_READ,     // READ
    TOKEN_KW_WRITE,    // WRITE
    TOKEN_KW_UNCOMMITTED, // UNCOMMITTED
    TOKEN_KW_COMMITTED,   // COMMITTED
    TOKEN_KW_REPEATABLE,  // REPEATABLE
    TOKEN_KW_SERIALIZABLE, // SERIALIZABLE

    // Prepared Statement Keywords
    TOKEN_KW_PREPARE,  // PREPARE
    TOKEN_KW_EXECUTE,  // EXECUTE
    TOKEN_KW_DEALLOCATE, // DEALLOCATE
    TOKEN_KW_AS,       // AS
    TOKEN_KW_USING,    // USING

    // JOIN Keywords
    TOKEN_KW_JOIN,     // JOIN / JODO
    TOKEN_KW_INNER,    // INNER
    TOKEN_KW_LEFT,     // LEFT
    TOKEN_KW_RIGHT,    // RIGHT
    TOKEN_KW_FULL,     // FULL
    TOKEN_KW_OUTER,    // OUTER
    TOKEN_KW_CROSS,    // CROSS
    TOKEN_KW_NATURAL,  // NATURAL
    TOKEN_KW_EXPLAIN,  // EXPLAIN / SAMJHAO
    TOKEN_KW_ANALYZE,  // ANALYZE
    TOKEN_KW_ORDER,    // ORDER
    TOKEN_KW_ASC,      // ASC
    TOKEN_KW_DESC,     // DESC
    TOKEN_KW_LIMIT,    // LIMIT
    TOKEN_KW_OFFSET,   // OFFSET
    TOKEN_KW_WHERE,    // WHERE

    // ALTER TABLE Keywords (Iteration 2)
    TOKEN_KW_ALTER,    // ALTER / BADLO_TABLE
    TOKEN_KW_ADD,      // ADD / JODO_COLUMN
    TOKEN_KW_COLUMN,   // COLUMN / STAMBH
    TOKEN_KW_RENAME,   // RENAME / NAAM_BADLO
    TOKEN_KW_MODIFY,   // MODIFY / SUDHAR
    TOKEN_KW_CONSTRAINT,// CONSTRAINT / NIYAM
    TOKEN_KW_FOREIGN,  // FOREIGN / VIDESHI
    TOKEN_KW_REFERENCES,// REFERENCES / SANDARBH
    TOKEN_KW_CASCADE,  // CASCADE / JHARNA
    TOKEN_KW_RESTRICT, // RESTRICT / ROKO
    TOKEN_KW_NULL,     // NULL / KHALI
    TOKEN_KW_NOT,      // NOT / NAHI
    TOKEN_KW_DEFAULT,  // DEFAULT / MOOL
    TOKEN_KW_UNIQUE,   // UNIQUE / ANOKHA

    // Backup/Restore Keywords
    TOKEN_KW_BACKUP,   // BACKUP / SURAKSHA
    TOKEN_KW_RESTORE,  // RESTORE / WAPAS_LAO
    TOKEN_KW_EXPORT,   // EXPORT / BHEJO
    TOKEN_KW_IMPORT,   // IMPORT / LAAO

    // NoSQL Enhanced Keywords
    TOKEN_KW_COLLECTION,// COLLECTION / SANGRAH
    TOKEN_KW_DOCUMENT, // DOCUMENT / DASTAVEZ
    TOKEN_KW_FIND,     // FIND / KHOJO
    TOKEN_KW_UPSERT,   // UPSERT / DAL_YA_BADLO
    TOKEN_KW_AGGREGATE,// AGGREGATE / IKATHA
    TOKEN_KW_MATCH,    // MATCH / MILA
    TOKEN_KW_PROJECT,  // PROJECT / PRADARSHI
    TOKEN_KW_UNWIND,   // UNWIND / KHOLO
    TOKEN_KW_LOOKUP,   // LOOKUP / DEKHO
    TOKEN_KW_SORT,     // SORT / KRAM_SE
    TOKEN_KW_FORMAT,   // FORMAT
    TOKEN_KW_DROP,     // DROP
    TOKEN_KW_DELETE,   // DELETE

    // Additional SQL Keywords
    TOKEN_KW_HAVING,   // HAVING / RAKHTE / JISME
    TOKEN_KW_DISTINCT, // DISTINCT / ALAG / MUKHTALIF
    TOKEN_KW_LIKE,     // LIKE / JAISA
    TOKEN_KW_IN,       // IN / ANDAR
    TOKEN_KW_BETWEEN,  // BETWEEN / BEECH
    TOKEN_KW_EXISTS,   // EXISTS / MAUJOOD
    TOKEN_KW_TRUE,     // TRUE / SACH / HAAN
    TOKEN_KW_FALSE,    // FALSE / JHOOTH / NA
    TOKEN_KW_CASE,     // CASE / MAAMLA
    TOKEN_KW_WHEN,     // WHEN / JAB
    TOKEN_KW_THEN,     // THEN / PHIR / TAB
    TOKEN_KW_ELSE,     // ELSE / WARNA
    TOKEN_KW_END,      // END / KHATAM

    // Cluster/Distributed Keywords
    TOKEN_KW_CLUSTER,  // CLUSTER / JHAAD
    TOKEN_KW_NODES,    // NODES / GRANTHI
    TOKEN_KW_REPLICATE,// REPLICATE / NAKAL
    TOKEN_KW_PARTITION,// PARTITION / VIBHAJAN
    TOKEN_KW_SYNC,     // SYNC / MILAO_SAATH

    // Help/Exit Commands
    TOKEN_KW_HELP,     // HELP / MADAD
    TOKEN_KW_QUIT,     // QUIT / NIKLO / BAHAR
    TOKEN_KW_EXIT,     // EXIT / KHATAM_KARO
    TOKEN_KW_STATUS,   // STATUS / HALAT / STHITI

    // Symbols
    TOKEN_LPAREN,
    TOKEN_RPAREN,
    TOKEN_COMMA,
    TOKEN_EQUALS,
    TOKEN_GT,
    TOKEN_LT,
    TOKEN_SEMICOLON,
    TOKEN_LBRACE,
    TOKEN_RBRACE,
    TOKEN_LBRACKET,    // [
    TOKEN_RBRACKET,    // ]
    TOKEN_COLON,
    TOKEN_STAR // *
} LexerTokenType;

typedef struct {
    LexerTokenType type;
    char *value;
    int line;
} Token;

typedef struct {
    Token *tokens;
    int count;
    int capacity;
} TokenList;

TokenList* tokenize(const char *input);
void free_token_list(TokenList *list);
const char* token_type_to_string(LexerTokenType type);

#endif
