#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <winsock2.h>
#include "distributed.h"
#include "storage.h" // For hash function

static int g_is_master = 0;
static WorkerNode g_workers[MAX_WORKERS];

void dist_init() {
    // Hardcoded workers for demo
    g_workers[0].ip = "127.0.0.1";
    g_workers[0].port = 8889;
    
    g_workers[1].ip = "127.0.0.1";
    g_workers[1].port = 8890;
}

void dist_set_master(int is_master) {
    g_is_master = is_master;
}

int dist_is_master() {
    return g_is_master;
}

// Helper to send to worker
char* send_to_worker(int worker_idx, const char *query) {
    if (worker_idx < 0 || worker_idx >= MAX_WORKERS) return strdup("Error: Invalid worker\n");
    
    // Create socket
    SOCKET sock;
    struct sockaddr_in server;
    
    sock = socket(AF_INET, SOCK_STREAM, 0);
    if (sock == INVALID_SOCKET) return strdup("Error: Socket failed (Master)\n");
    
    server.sin_addr.s_addr = inet_addr(g_workers[worker_idx].ip);
    server.sin_family = AF_INET;
    server.sin_port = htons(g_workers[worker_idx].port);
    
    if (connect(sock, (struct sockaddr *)&server, sizeof(server)) < 0) {
        char err[64];
        sprintf(err, "Error: Connection to Worker %d failed\n", worker_idx);
        return strdup(err);
    }
    
    // Send
    send(sock, query, strlen(query), 0);
    send(sock, "\n", 1, 0); // Ensure newline
    
    // Receive Response with EOF Protocol
    int buf_size = 4096;
    int total = 0;
    char *response = malloc(buf_size);
    response[0] = '\0';
    
    char buffer[1024];
    int len;
    
    while ((len = recv(sock, buffer, 1023, 0)) > 0) {
        buffer[len] = 0;
        
        // Check resizing
        if (total + len >= buf_size) {
            buf_size *= 2;
            response = realloc(response, buf_size);
        }
        
        // Append
        strcat(response, buffer);
        total += len;
        
        // Check for Marker
        char *marker = strstr(response, "<<EOF>>");
        if (marker) {
            *marker = '\0'; // Strip marker
            break;
        }
    }
    
    closesocket(sock);
    
    if (total > 0) return response;
    free(response);
    return strdup("No response\n");
}

// Helper to hashing string
static unsigned long dist_hash_djb2(const char *str) {
    unsigned long hash = 5381;
    int c;
    while ((c = *str++))
        hash = ((hash << 5) + hash) + c; /* hash * 33 + c */
    return hash;
}

char* dist_route_query(ASTNode *node, const char *raw_query) {
    if (!node) return NULL;
    
    int target_worker = -1;
    
    // 1. Partitioning Logic (INSERT)
    if (node->type == NODE_CMD_INSERT) {
        // Assume ID/PK is the First Column Value for convenience
        // Step 8 requires hash partitioning.
        if (node->data.insert.rows) {
             // Minimal fix for compilation: Default to worker 0 for now
             target_worker = 0;
        }
    } 
    // 2. Partitioning Logic (SELECT/DELETE/UPDATE) - Point Lookups
    else if (node->type == NODE_CMD_SELECT || node->type == NODE_CMD_DELETE) {
        // Check WHERE clause for "id = X"
        ASTNode *cond = (node->type == NODE_CMD_SELECT) ? node->data.select.where_clause : node->data.delete_stmt.where_clause;
        
        if (cond && cond->type == NODE_EXPR_BINARY) {
             char *col = cond->data.binary_expr.left->data.literal.value;
             char *op = cond->data.binary_expr.op;
             ASTNode *rhs = cond->data.binary_expr.right;
             
             if (strcmp(col, "id") == 0 && strcmp(op, "=") == 0 && rhs->type == NODE_EXPR_LITERAL) {
                 char *id = rhs->data.literal.value;
                 target_worker = dist_hash_djb2(id) % MAX_WORKERS;
             }
        }
    }
    // 3. Document Store Partitioning
    else if (node->type == NODE_CMD_DOC_INSERT) {
        // RAKHO col <json> (ID is generated? Or inside JSON?)
        // If ID is auto-generated by executor, Master needs to generate it to route it?
        // Or route random?
        // Let's assume random/round-robin for DOC INSERT if no ID specified, 
        // OR better: Execute locally on Master to gen ID? No.
        // Simple: Round Robin.
        static int rr = 0;
        target_worker = (rr++) % MAX_WORKERS;
    }
    else if (node->type == NODE_CMD_DOC_GET || node->type == NODE_CMD_DOC_REMOVE) {
        // DHUNDO - If parsing extracted ID?
        // Parser for DHUNDO extraction needs checking.
        // Currently execute_doc_get handles "MANGWAO" (Get All) and "DHUNDO" (Get One).
        if (node->type == NODE_CMD_DOC_GET && node->data.doc_get.doc_id != NULL) {
             target_worker = dist_hash_djb2(node->data.doc_get.doc_id) % MAX_WORKERS;
        }
        else if (node->type == NODE_CMD_DOC_REMOVE && node->data.doc_remove.doc_id != NULL) {
             target_worker = dist_hash_djb2(node->data.doc_remove.doc_id) % MAX_WORKERS;
        }
    }

    if (target_worker != -1) {
        // Route to specific worker
        printf("[Master] Routing Query to Worker %d (Hashed)\n", target_worker);
        return send_to_worker(target_worker, raw_query);
    } else {
        // Broadcast (Scatter-Gather)
        // Cases: Full Scan SELECT, CREATE TABLE, DROP TABLE, SHOW TABLES ...
        printf("[Master] Broadcasting Query to All Workers\n");
        char *result = malloc(16384); // 16KB Result Buffer
        result[0] = 0;
        int offset = 0;
        
        for(int i=0; i<MAX_WORKERS; i++) {
            char *part = send_to_worker(i, raw_query);
            if (part) {
                // If SELECT, try to strip headers for subsequent workers?
                // Simplification for now: Just append.
                if (offset + strlen(part) < 16380) {
                    strcat(result, part);
                    offset += strlen(part);
                    // Add separator
                    strcat(result, "\n"); 
                    offset++;
                }
                free(part);
            }
        }
        return result;
    }
    return NULL; // Should not reach here
}
